
create database Retail_Sales_Db

SELECT * FROM Retail_Sales_Dataset

alter table Retail_Sales_Dataset
alter column "sales_amount" decimal(10,2)

select count (*) as missing_unit_price
from Retail_Sales_Dataset
where unit_price is null

select distinct category
from retail_sales_dataset

select distinct brand
from retail_sales_dataset

select distinct payment_method
from retail_sales_dataset

select distinct sales_channel
from retail_sales_dataset

select distinct product_name
from retail_sales_dataset

select distinct region
from retail_sales_dataset

-----23/05/2026 

--------------ANALYSIS------
----1. Sales Performance Analysis-------
---a. What is the total revenue generated by the company?

select sum(sales_amount) as Total_Revenue
from Retail_Sales_Dataset
-------The total revenue generated is 45,357,054.45

---b. total quantity sold?

select * from Retail_Sales_Dataset
select sum(quantity) as Total_quantity_sold
from Retail_Sales_Dataset
---- the total quantity sold is 199549

--- c average order value

select AVG(sales_amount) as average_order_value
from Retail_Sales_Dataset
-----it is 3777.975453

------2. Product Category Performance -----
--- The percentage of each category by total revenue:
select category, sum(sales_amount) as revenue, 
ROUND(sum(sales_amount) * 100.0 / 
(select sum(sales_amount) from Retail_sales_dataset),2) 
as revenue_percentage from Retail_Sales_Dataset 
group by category
order by revenue desc

---- question a: Which product categories performed best --
select top 5 category, sum(sales_amount) as Highest_Revenue_Categories
from Retail_Sales_Dataset
group by category
order by Highest_Revenue_Categories desc

/* Beauty is the highest performing category, generating 6,355,718.23 in revenue and accounting for 14.01% of the total
revenue */

----b. which product category sells the highest quantity of products
select  category, sum(quantity) as Highest_quantity
from Retail_Sales_Dataset
group by category
order by Highest_quantity desc

/* clothing has 25223 quantity of products sold, while Beauty with the highest revenue has 25171 number of 
total quantity of products sold */

---c. the lowest performing categories
select top 5 category, sum(sales_amount) as Lowest_revenue_categories
from Retail_Sales_Dataset
group by category
order by Lowest_revenue_categories asc

/*-clothing generated the lowest revenue, but it is actually the category that sells the highest quantity of products,
this shows that clothing products are actually cheap and affordable therefore people tend to purchase it more, but the
revenue generation is low because of its low sales price. This is followed by Groceries, Toys, Home and Electronics 
with just little differences in the revenue generation.*/

---3.  BRAND PERFORMANCE ANALYSIS -----

--Brand by revenue percentage calculation
select brand, sum(sales_amount) as revenue,
round(sum(sales_amount) * 100.0 /
(select sum(sales_amount) from Retail_Sales_dataset),2)
as revenue_percentage from Retail_Sales_Dataset
group by brand
order by revenue desc


---- a. TOP REVENUE-GENERATING BRANDS?
Select  brand, sum(sales_amount) as Top_Revenues
from Retail_Sales_Dataset
group by brand
order by Top_Revenues desc

----Brand 2 generated the highest revenue 15,948,868.44 and accounts for 35.16% of the total revenue

--- b. LOWEST-PERFORMING BRANDS
Select  brand, sum(sales_amount) as Lowest_Revenues
from Retail_Sales_Dataset
group by brand
order by Lowest_Revenues asc

--- Brand 1 performed the least in terms of revenue generation and accounts for 30% of the total revenue

----- 4. REGIONAL PERFORMANCE ANALYSIS  ----

-- a.  Revenue by Region
select region, Sum(sales_amount) as Revenue_by_Region
from Retail_Sales_Dataset
group by region
order by Revenue_by_Region desc

/* Central Region generated the highest revenue of 9,237,924.11 which accounts for 20% 
while East region generated the lowest revenue*/

--- b. Quantity sold by region
select region, Sum(quantity) as Quantity_by_Region
from Retail_Sales_Dataset
group by region
order by Quantity_by_Region desc

----- Central Region also sold the highest quantity, East Region sold the lowest quantity

-- 5. CUSTOMER DEMOGRAPHICS ANALYSIS
--- QUESTION: WHO ARE THE MOST VALUABLE CUSTOMERS?

--- a. Revenue by age group
select customer_age_group, sum(sales_amount) as Revenue_by_age_group
from Retail_Sales_Dataset
group by customer_age_group
order by Revenue_by_age_group desc

--- The age group of 35-44 generated the highest revenue of 9,170,231.38

select * from Retail_Sales_Dataset

-- b Revenue by gender
select customer_gender,sum(sales_amount) as Revenue_by_gender
from Retail_Sales_Dataset
group by customer_gender
order by Revenue_by_gender desc

---Female gender has highest revenue of 15,182,360.93

-- c. Highest spending customer-segment

select customer_segment,sum(sales_amount) as Revenue_by_Customer_Segment
from Retail_Sales_Dataset
group by customer_segment
order by Revenue_by_Customer_Segment desc

---The Loyal customer segment spends the most

-- 6. PAYMENT METHOD ANALYSIS ---
-- Question: How do customers prefer to pay?

--- a. Most used payment method
select top 1 payment_method, COUNT(*) as usage_count
from Retail_Sales_Dataset
group by payment_method
order by usage_count desc

--- This is Credit Card, the most used payment method

--- b. Revenue by payment method

select payment_method, sum(sales_amount) as Revenue_by_payment_method
from Retail_Sales_Dataset
group by payment_method
order by Revenue_by_payment_method desc

---- Cash generated the highest revenue of 9,134,699.83 

-- c. Payment behaviour across customer_age_group
select * from Retail_Sales_Dataset
select payment_method,customer_age_group, count(*) as Total_transactions
from Retail_Sales_Dataset
GROUP BY customer_age_group, payment_method
order by customer_age_group, Total_transactions desc

---- 7. DISCOUNT IMPACT ANALYSIS
---- QUESTION: Do Discounts improve sales?

---a. Sales under different discount levels
select discount_pct, sum(sales_amount) as sales
from Retail_Sales_Dataset
group by discount_pct
order by sales desc

--- b. Quantity sold by discount level
select discount_pct, sum(quantity) as Quantity_Sold
from Retail_Sales_Dataset
group by discount_pct
order by Quantity_Sold desc

--c. Comparison of discountdd and non discounted products
select discount_pct, count(*) as transactions,
sum(quantity) as quantity_sold,
sum(sales_amount) as Total_revenue
from Retail_Sales_Dataset
group by discount_pct
order by discount_pct 

/* The analysis suggests that discounts did not significantly improve sales performance. Products sold without 
discounts generated both the highest revenue and the highest sales volume, indicating that customers were willing 
to purchase even at full price*/

--- 8. CUSTOMER PRODUCT BEHAVIOUR
--- QUESTION: WHAT PRODUCTS DO DIFFERENT CUSTOMER GROUPS PREFER

-- a. Category preference by age group
select  customer_age_group, category, sum(sales_amount) as Revenue
from Retail_Sales_Dataset
group by category, customer_age_group
order by customer_age_group, Revenue desc

-- b. category preference by gender
select customer_gender, category, SUM(Sales_amount) as Total_sales
from Retail_Sales_Dataset
group by category, customer_gender
order by customer_gender, Total_sales desc


--- 9. REGIONAL PRODUCT PERFORMANCE
--- QUESTION: WHICH PRODUCTS SUCCEED IN EACH REGION?

---a.  Top categories per region
select region, category, sum(sales_amount) as Total_revenue
from Retail_Sales_Dataset
group by category, region
order by region,Total_revenue desc

--- b. Top brands per region
select region,brand, sum(sales_amount) as Sales
from Retail_Sales_Dataset
group by brand, region
order by region, Sales desc

--- c. Region with the highest potential
select region, sum(sales_amount) as Total_revenue
from Retail_Sales_Dataset
group by region
order by Total_revenue desc

--- 10. REVENUE DRIVERS AND BUSINESS OPPORTUNITIES
-- QUESTION: WHAT FACTORS SEEM TO DRIVE HIGHER SALES?

--- a. Which customer age groups spend the most?
select customer_age_group, sum(sales_amount) as Revenue_by_age_group
from Retail_Sales_Dataset
group by customer_age_group
order by Revenue_by_age_group desc


--- b. Which categories generate the highest revenue?
select top 5 category, sum(sales_amount) as Highest_Revenue_Categories
from Retail_Sales_Dataset
group by category
order by Highest_Revenue_Categories desc


/*--- BUSINESS ANALYSIS, INSIGTHS AND RECOMMENDATION  ------

--- 1. OVERALL SALES PERFORMANCE
The business generated a total revenue of 45,357,054.45 from 12,000 transactions, with 199549 units sold. The average
order value was 3777.975453, indicating the average amount spent per transaction.

--- 2. PRODUCT CATEGORY PERFORMANCE
Highest Revenue Category
 Beauty is the highest performing category, generating 6,355,718.23 in revenue and accounting for 14.01% of the total
revenue. This indicates strong customer demand and significant contribution to business performance.
Lowest Revenue Category
 Clothing generated the lowest revenue 4,628,379.45  among all categories, contributing 10%. This may indicate 
 lower customer demand or an opportunity for improved marketing and sales strategies.

--- 3. BRAND PERFORMANCE
  Brand 2  was the top performing brand, generating 15,948,868.44  in sales revenue and contributing the largest 
  share of total sales. Brand 1 generated the lowest revenue of 13,623,017.08, suggesting potential opportunities to 
  improve product visibility and customer engagement.

----4. REGIONAL PERFORMANCE
The Central region generated the highest revenue of 9,237,924.11, making it the strongest performing region 
during the analysis period. The East region recorded the lowest revenue of 8,971,517.64 indicating potential areas 
for business growth and market expansion.

---- 5. CUSTOMER DEMOGRAPHIC ANALYSIS
Highest Spending Age Group
Customers aged 35-44 generated the highest revenue of 9,170,231.38, making them the most valuable customer segment 
in the dataset.
Highest Spending Gender
Female customers contributed the highest sales revenue generating 15,182,360.93, and representing the most
 profitable customer group.

-- 6. PAYMENT METHOD ANALYSIS
The most used payment method was 'credit card' ,indicating a strong customer preference for this payment option.
Transactions completed using 'Cash' generated the highest revenue of 9,134,699.83, highligthing its importance in 
overall sales performance.

--- 7. DISCOUNT ANALYSIS
The analysis suggests that discounts did not significantly improve sales performance. Products sold without 
discounts generated both the highest revenue and the highest sales volume,indicating that customers were willing to 
purchase even at full price

--- 8. CATEGORY PERFORMANCE BY REGION
In the Central region, Beauty was the highest performing category, generating 1,347,394.43 in sales. This suggests 
strong regional demand for products within this category.

--- 9. BUSINESS RECOMMENDATION
Based on the findings, the business should proritize investment in high performing product categories and customer
segments while implementing targeted strategies to improve performance in underperforming regions and categories.*/










